# Read more: https://docs.gitlab.com/12.7/ee/ci/yaml/README.html
cache:
    paths:
        - .yarn
        - node_modules/

before_script:
    - yarn install --cache-folder .yarn

stages:
    - static-checking
    - type-checking
    - test
    - build

static-checking:
    stage: static-checking
    script:
        - yarn eslint
    only:
        - merge_requests
        - dev

type-checking:
    stage: type-checking
    script:
        - yarn check-types
    only:
        - merge_requests
        - dev

test:
    stage: test
    script:
        - yarn test
    only:
        - merge_requests
        - dev

build:
    stage: build
    script:
        - yarn build
    only:
        - dev
